export const teamList = ['russia',
  'saudi arabia',
  'egypt',
  'uruguay',
  'portugal',
  'spain',
  'morocco',
  'iran',
  'france',
  'australia',
  'peru',
  'denmark',
  'argentina',
  'iceland',
  'croatia',
  'nigeria',
  'brazil',
  'switzerland',
  'costa rica',
  'serbia',
  'germany',
  'mexico',
  'sweden',
  'korea republic',
  'belgium',
  'panama',
  'tunisia',
  'england',
  'poland',
  'senegal',
  'colombia',
  'japan'];

export const x = [480, 2540];

export const y = [143, 670, 1190, 1710, 143, 670, 1193, 1695];
